@apiKey = set_api_key
@namespace = test-automation
@dashboardTitle = Test Automation Metrics
@dashboardId = set_here_dashboard_id

### Get Dashboard by Title
GET http://localhost:5601/s/{{namespace}}/api/saved_objects/_find?type=dashboard&search_fields=title&search={{dashboardTitle}}&per_page=10
Content-Type: application/json
Authorization: ApiKey {{apiKey}}
kbn-xsrf: true


### Get Dashboard by ID (replace dashboard_id with the actual ID from the previous request)
GET http://localhost:5601/s/{{namespace}}/api/saved_objects/dashboard/{{dashboardId}}
Content-Type: application/json
Authorization: ApiKey {{apiKey}}
kbn-xsrf: true

### Export Dashboard (replace dashboard_id with the actual ID)
POST http://localhost:5601/s/{{namespace}}/api/saved_objects/_export
Content-Type: application/json
Authorization: ApiKey {{apiKey}}
kbn-xsrf: true

{
  "objects": [
    {
      "type": "dashboard",
      "id": "{{dashboardId}}"
    }
  ],
  "includeReferencesDeep": true
}