@apiKey = set_api_key
@namespace = test-automation

### Import Dashboard
POST http://localhost:5601/s/{{namespace}}/api/saved_objects/_import?overwrite=true
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: ApiKey {{apiKey}}
kbn-xsrf: true

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="dashboard_export.ndjson"
Content-Type: application/ndjson

< ./dashboard_export.ndjson
------WebKitFormBoundary7MA4YWxkTrZu0gW--